# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.
default_velocity_scaling_factor: 0.3
default_acceleration_scaling_factor: 0.3

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_velocity_limits: true
    max_velocity: 2.36
    has_acceleration_limits: true
    max_acceleration: 4.72
  joint2:
    has_velocity_limits: true
    max_velocity: 2.36
    has_acceleration_limits: true
    max_acceleration: 4.72
  joint3:
    has_velocity_limits: true
    max_velocity: 2.36
    has_acceleration_limits: true
    max_acceleration: 4.72
  joint4:
    has_velocity_limits: true
    max_velocity: 2.36
    has_acceleration_limits: true
    max_acceleration: 4.72
  joint5:
    has_velocity_limits: true
    max_velocity: 2.36
    has_acceleration_limits: true
    max_acceleration: 4.72
  joint6:
    has_velocity_limits: true
    max_velocity: 2.36
    has_acceleration_limits: true
    max_acceleration: 4.72